export const STATUS = {
  LOADING: "LOADING",
  ERROR: "ERROR",
  READY: "READY",
  ACTIVE: "ACTIVE",
  FINISHED: "FINISHED",
  REVIEW: "REVIEW",
};
export const ACTIONS = {
  DATA_RECEIVED: "DATARECEIVED",
  DATA_LOADING: "DATA_LOADING",
  DATA_FAILED: "DATA_FAILED",
  START_QUIZ: "START_QUIZ",
  SAVE_ANSWER: "SAVE_ANSWER",
  NEXT_QUESTION: "NEXT_QUESTION",
  FINISH: "FINISH",
  REVIEW_QUIZ: "REVIEW_QUIZ",
  TIMEOUT: "TIMEOUT",
  RETAKE_QUIZ: "RETAKE_QUIZ",
};
